# -*- coding: utf-8 -*-
"""xG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eQIJs3h7jm0dIFwpaU4lrVvCuP7jAfPi
"""

import pandas as pd
import numpy as np
from scipy.stats import poisson
import seaborn as sns
import matplotlib.pyplot as plt


pd.set_option('display.max_rows', 1000)

url = 'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'

epl_list = []

epl_list.append(pd.read_html(url,index_col=False,flavor='lxml')[0])

epl_list = pd.concat(epl_list, axis=0, ignore_index=True)

epl_df = epl_list[epl_list['Wk'].notna()]

epl_df = epl_df.rename(columns={'xG':'xGHome'
                   ,'xG.1':'xGAway'})

print(epl_df.columns.tolist())

epl_df['HomeScore'] = epl_df['Score'].str[0]
epl_df['AwayScore'] = epl_df['Score'].str[2]

epl_df = epl_df.drop(['Match Report','Notes'],axis=1)

epl_df['Date'] = pd.to_datetime(epl_df['Date'])

print(epl_df.head(5))

epl_df.sort_values(by='Date', inplace=True)

epl_df = epl_df[['Wk','Day','Date','Time','Home','HomeScore','xGHome','AwayScore','xGAway','Away','Attendance','Venue','Referee']]

epl_df = epl_df.dropna()

epl_df = epl_df[['Date','Home','HomeScore','xGHome','AwayScore','xGAway','Away']].reset_index(drop=True)

epl_df

league_Mean_Home_xG = round((epl_df['xGHome'].mean()),2)
league_Mean_Away_xG = round((epl_df['xGAway'].mean()),2)

print(f'The mean home expected goals is {league_Mean_Home_xG}')
print(f'The mean away expected goals is {league_Mean_Away_xG}')

home_team_xg_strength_offense = epl_df.groupby('Home').agg({'xGHome': 'sum', 'Home': ['count', 'first']})

home_team_xg_strength_offense

home_team_xg_strength_offense.columns = ['xGHome', 'TotalGames', 'Home']

home_team_xg_strength_offense['xGHome_offense_rating'] = (home_team_xg_strength_offense['xGHome'] / home_team_xg_strength_offense['TotalGames']) / league_Mean_Home_xG

home_team_xg_strength_offense = home_team_xg_strength_offense.reset_index(drop = True)

home_team_xg_strength_offense = pd.DataFrame(home_team_xg_strength_offense)

home_team_xg_strength_offense.columns = ['xGHome', 'TotalGames','Home','xGHome_offense_rating']

home_team_xg_strength_offense = home_team_xg_strength_offense[['Home','xGHome','TotalGames','xGHome_offense_rating']]

home_team_xg_strength_offense.sort_values('xGHome_offense_rating', ascending=False)

away_team_xg_strength_offense = epl_df.groupby('Away').agg({'xGAway':'sum', 'Away':['count','first']})

away_team_xg_strength_offense.columns = ['xGAway','TotalGames','Away']

away_team_xg_strength_offense['xGAway_offense_rating'] = (away_team_xg_strength_offense['xGAway']/away_team_xg_strength_offense['TotalGames'])/league_Mean_Away_xG

away_team_xg_strength_offense

away_team_xg_strength_offense = away_team_xg_strength_offense.reset_index(drop = True)

away_team_xg_strength_offense = pd.DataFrame(away_team_xg_strength_offense)

away_team_xg_strength_offense.sort_values('xGAway_offense_rating',ascending=False)

home_team_xg_strength_defense = epl_df.groupby('Home').agg({'xGAway': 'sum', 'Home': ['count', 'first']})

home_team_xg_strength_defense

home_team_xg_strength_defense.columns = ['xGAway', 'TotalGames', 'Home']

home_team_xg_strength_defense['xGHome_defense_rating'] = (home_team_xg_strength_defense['xGAway'] / home_team_xg_strength_defense['TotalGames']) / league_Mean_Away_xG

home_team_xg_strength_defense = home_team_xg_strength_defense.reset_index(drop = True)

home_team_xg_strength_defense.sort_values('xGHome_defense_rating')

home_team_xg_strength_defense = home_team_xg_strength_defense.rename(columns={'xGAway':'xG_Conceded_at_Home'})

away_team_xg_strength_defense = epl_df.groupby('Away').agg({'xGHome': 'sum', 'Away': ['count', 'first']})

away_team_xg_strength_defense

away_team_xg_strength_defense.columns = ['xG_Conceded_at_Away', 'TotalGames', 'Away']

away_team_xg_strength_defense['xGAway_defense_rating'] = (away_team_xg_strength_defense['xG_Conceded_at_Away'] / away_team_xg_strength_defense['TotalGames']) / league_Mean_Home_xG

away_team_xg_strength_defense = away_team_xg_strength_defense.reset_index(drop = True)

away_team_xg_strength_defense.sort_values('xGAway_defense_rating')

chelsea_home_offense_rating = 0.916056
liverpool_away_defense_rating = 1.019320

chelsea_home_expected_xg = (chelsea_home_offense_rating * liverpool_away_defense_rating) * league_Mean_Home_xG

liverpool_away_offense_rating = 1.332498
chelsea_home_defense_rating = 0.981621

liverpool_away_expected_xg = (liverpool_away_offense_rating * chelsea_home_defense_rating) * league_Mean_Away_xG

chelsea_home_expected_xg

liverpool_away_expected_xg

"""Poisson Distribution to calculate the probabilites of the match result

"""

home_expectancy = chelsea_home_expected_xg
away_expectancy = liverpool_away_expected_xg


max_score = 7
score_range = np.arange(0, max_score+1)

home_pmf = poisson.pmf(score_range, home_expectancy)
away_pmf = poisson.pmf(score_range, away_expectancy)

# calculate the outer product of the home and away PMFs
score_prob_matrix = np.outer(home_pmf, away_pmf)

# reshape the matrix into a square matrix of score probabilities
score_prob_matrix = score_prob_matrix.reshape(max_score+1, max_score+1)


# set the figure size
fig, ax = plt.subplots(figsize=(12, 8))

# create a heatmap using seaborn
sns.set()
sns.heatmap(score_prob_matrix, cmap="coolwarm", annot=True, fmt=".4f", square=True, cbar_kws={"shrink": 0.7}, ax=ax)

# set the axis labels and title
plt.xlabel("Away goals")
plt.ylabel("Home goals")
plt.title("Score probability matrix")

# display the plot
plt.show()